FROM golang:1.22 AS build

WORKDIR /src
COPY services/media_edge ./services/media_edge
WORKDIR /src/services/media_edge
RUN go build -trimpath -ldflags='-s -w' -o /out/memoria-media-edge ./cmd/mediaruntime

FROM gcr.io/distroless/base-debian12:nonroot

ARG MEMORIA_RELEASE_COMMIT
ARG MEMORIA_RELEASE_TAG
LABEL org.opencontainers.image.revision="${MEMORIA_RELEASE_COMMIT}" \
      org.opencontainers.image.version="${MEMORIA_RELEASE_TAG}" \
      com.memoria.release.role="media-edge"

COPY --from=build /out/memoria-media-edge /usr/local/bin/memoria-media-edge
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/memoria-media-edge"]
