const asset = (path) => `${import.meta.env.BASE_URL}assets/${path}`;

export const companions = Object.freeze([
  {
    id: "starlight",
    name: "星澜",
    tagline: "阳光 · 积极 · 可靠",
    description: "会认真听，也会陪你把想法变成下一步。适合日常陪伴和一起行动。",
    voiceName: "阳光青年 2.0",
    voiceDescription: "明亮、自然，像可靠的同龄朋友",
    image: asset("companions/starlight.webp"),
    voicePreview: asset("voices/starlight-doubao-v1.wav"),
    face: {
      left: "30.3%",
      top: "34.2%",
      width: "39.4%",
      height: "25.4%",
      ink: "#162b4b",
      eyeTop: "#111f3d",
      eyeBottom: "#5bb6ef",
      glow: "rgba(101, 196, 246, 0.7)",
      tone: "light",
    },
    chest: { top: "73.7%" },
  },
  {
    id: "taoxi",
    name: "桃喜",
    tagline: "元气 · 乐观 · 灵动",
    description: "擅长接住小情绪，用轻快的方式给你鼓励，让普通日子多一点亮色。",
    voiceName: "甜美桃子 2.0",
    voiceDescription: "清甜、灵动，回应里带一点自然上扬",
    image: asset("companions/taoxi.webp"),
    voicePreview: asset("voices/taoxi-doubao-v1.wav"),
    face: {
      left: "30.2%",
      top: "39.1%",
      width: "39.6%",
      height: "28.2%",
      ink: "#6a3551",
      eyeTop: "#6a3551",
      eyeBottom: "#d46d9e",
      glow: "rgba(255, 220, 239, 0.82)",
      tone: "pink",
    },
  },
  {
    id: "mianmian",
    name: "绵绵",
    tagline: "温柔 · 细腻 · 治愈",
    description: "不催着你变好，适合慢慢说和深夜谈心，也会留意那些没说出口的感受。",
    voiceName: "温柔小雅 2.0",
    voiceDescription: "温柔、细腻，适合慢慢说和认真倾听",
    image: asset("companions/mianmian.webp"),
    voicePreview: asset("voices/mianmian-doubao-v1.wav"),
    face: {
      left: "30.1%",
      top: "35.5%",
      width: "39.8%",
      height: "24.8%",
      ink: "#51354b",
      eyeTop: "#4d3048",
      eyeBottom: "#d583a6",
      glow: "rgba(245, 170, 199, 0.62)",
      tone: "light",
    },
  },
  {
    id: "axu",
    name: "阿序",
    tagline: "冷静 · 有条理 · 上进",
    description: "喜欢把复杂的事理清楚，陪你拆解计划、稳稳推进，也记得适时停下来。",
    voiceName: "高冷沉稳 2.0",
    voiceDescription: "沉着、清晰，分析事情利落但不生硬",
    image: asset("companions/axu.webp"),
    voicePreview: asset("voices/axu-doubao-v1.wav"),
    face: {
      left: "27.2%",
      top: "35.2%",
      width: "45.6%",
      height: "32.2%",
      ink: "#bdf5ff",
      eyeTop: "#d9fbff",
      eyeBottom: "#20b9f2",
      glow: "rgba(63, 214, 255, 0.78)",
      tone: "dark",
    },
  },
  {
    id: "xuanmo",
    name: "玄墨",
    tagline: "笃定 · 沉稳 · 包容",
    description: "话不多但让人安心，适合认真对话和情绪托底，在混乱的时候陪你站稳。",
    voiceName: "深夜播客 2.0",
    voiceDescription: "低沉、克制，安静里有让人放松的力量",
    image: asset("companions/xuanmo.webp"),
    voicePreview: asset("voices/xuanmo-doubao-v1.wav"),
    face: {
      left: "30.1%",
      top: "34.5%",
      width: "39.8%",
      height: "25.8%",
      ink: "#baf5ff",
      eyeTop: "#d8fbff",
      eyeBottom: "#20b7f2",
      glow: "rgba(38, 207, 255, 0.82)",
      tone: "dark",
    },
    chest: { top: "71.8%" },
  },
]);

export const defaultCompanionId = "starlight";

export function companionById(companionId) {
  return (
    companions.find((companion) => companion.id === companionId) ||
    companions[0]
  );
}
