const asset = (path) => `${import.meta.env.BASE_URL}assets/${path}`;

export const companions = Object.freeze([
  {
    id: "starlight",
    name: "星澜",
    tagline: "温暖回应 · 适度追问 · 1–3 句",
    description: "回应有温度，也会偶尔追问一层，适合日常聊天和中等深度的梳理。",
    voiceName: "阳光青年 2.0",
    voiceDescription: "明亮、自然，像可靠的同龄朋友",
    image: asset("companions/starlight.webp"),
    voicePreview: asset("voices/starlight-doubao-v1.wav"),
    face: {
      left: "30.3%",
      top: "34.2%",
      width: "39.4%",
      height: "25.4%",
      ink: "#162b4b",
      eyeTop: "#111f3d",
      eyeBottom: "#5bb6ef",
      glow: "rgba(101, 196, 246, 0.7)",
      tone: "light",
    },
    chest: { top: "73.7%" },
  },
  {
    id: "taoxi",
    name: "桃喜",
    tagline: "轻快回应 · 少量追问 · 1–2 句",
    description: "语气更轻快，回复偏短，较少连续追问，适合轻松说说当天的事。",
    voiceName: "甜美桃子 2.0",
    voiceDescription: "清甜、灵动，回应里带一点自然上扬",
    image: asset("companions/taoxi.webp"),
    voicePreview: asset("voices/taoxi-doubao-v1.wav"),
    face: {
      left: "30.2%",
      top: "39.1%",
      width: "39.6%",
      height: "28.2%",
      ink: "#6a3551",
      eyeTop: "#6a3551",
      eyeBottom: "#d46d9e",
      glow: "rgba(255, 220, 239, 0.82)",
      tone: "pink",
    },
  },
  {
    id: "mianmian",
    name: "绵绵",
    tagline: "慢慢倾听 · 低频追问 · 2–3 句",
    description: "会留出更多表达空间，追问频率较低；你愿意时，再陪你聊得更深。",
    voiceName: "温柔小雅 2.0",
    voiceDescription: "温柔、细腻，适合慢慢说和认真倾听",
    image: asset("companions/mianmian.webp"),
    voicePreview: asset("voices/mianmian-doubao-v1.wav"),
    face: {
      left: "30.1%",
      top: "35.5%",
      width: "39.8%",
      height: "24.8%",
      ink: "#51354b",
      eyeTop: "#4d3048",
      eyeBottom: "#d583a6",
      glow: "rgba(245, 170, 199, 0.62)",
      tone: "light",
    },
  },
  {
    id: "axu",
    name: "阿序",
    tagline: "直接梳理 · 低频追问 · 1–3 句",
    description: "表达更直接，擅长把信息整理清楚，但不会替你决定应该成为什么样的人。",
    voiceName: "高冷沉稳 2.0",
    voiceDescription: "沉着、清晰，分析事情利落但不生硬",
    image: asset("companions/axu.webp"),
    voicePreview: asset("voices/axu-doubao-v1.wav"),
    face: {
      left: "27.2%",
      top: "35.2%",
      width: "45.6%",
      height: "32.2%",
      ink: "#bdf5ff",
      eyeTop: "#d9fbff",
      eyeBottom: "#20b9f2",
      glow: "rgba(63, 214, 255, 0.78)",
      tone: "dark",
    },
  },
  {
    id: "xuanmo",
    name: "玄墨",
    tagline: "克制回应 · 很少追问 · 1–2 句",
    description: "回复更克制、留白更多，通常不主动深挖；只有你明确邀请时才进入深访。",
    voiceName: "深夜播客 2.0",
    voiceDescription: "低沉、克制，安静里有让人放松的力量",
    image: asset("companions/xuanmo.webp"),
    voicePreview: asset("voices/xuanmo-doubao-v1.wav"),
    face: {
      left: "30.1%",
      top: "34.5%",
      width: "39.8%",
      height: "25.8%",
      ink: "#baf5ff",
      eyeTop: "#d8fbff",
      eyeBottom: "#20b7f2",
      glow: "rgba(38, 207, 255, 0.82)",
      tone: "dark",
    },
    chest: { top: "71.8%" },
  },
]);

export const defaultCompanionId = "starlight";

export function companionById(companionId) {
  return (
    companions.find((companion) => companion.id === companionId) ||
    companions[0]
  );
}
