#!/usr/bin/env python3
"""Create root-only PostgreSQL and MinIO bootstrap env files."""

from __future__ import annotations

import argparse
import os
import secrets
import tempfile
from pathlib import Path

from scripts.production_postgres_roles import PRODUCTION_POSTGRES_ROLES


def _write_new(path: Path, values: dict[str, str]) -> None:
    if path.exists():
        raise FileExistsError(f"refusing to replace existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="ascii") as stream:
            stream.write("# Generated by bootstrap_production_data_env.py\n")
            for key in sorted(values):
                stream.write(f"{key}={values[key]}\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.link(temporary, path)
        temporary.unlink()
    finally:
        temporary.unlink(missing_ok=True)


def _secret() -> str:
    return secrets.token_urlsafe(48)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--postgres", type=Path, default=Path("/etc/memoria-postgres.env"))
    parser.add_argument("--minio", type=Path, default=Path("/etc/memoria-minio.env"))
    args = parser.parse_args()
    _write_new(
        args.postgres,
        {
            "POSTGRES_PASSWORD": _secret(),
            **{role.password_env: _secret() for role in PRODUCTION_POSTGRES_ROLES},
        },
    )
    _write_new(
        args.minio,
        {
            "MINIO_ROOT_USER": f"mroot{secrets.token_hex(6)}",
            "MINIO_ROOT_PASSWORD": _secret(),
            "MEMORIA_ARCHIVE_OBJECT_ACCESS_KEY": f"marchive{secrets.token_hex(6)}",
            "MEMORIA_ARCHIVE_OBJECT_SECRET_KEY": _secret(),
            "MEMORIA_VOICE_OBJECT_ACCESS_KEY": f"mvoice{secrets.token_hex(6)}",
            "MEMORIA_VOICE_OBJECT_SECRET_KEY": _secret(),
        },
    )
    print(f"created root-only env files: {args.postgres}, {args.minio}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
