"""Run the fixed static/append-only/evolving self-evolution evaluation."""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path

from services.evolution.evaluation import (
    default_evolution_tasks,
    evaluate_all_modes,
    evaluate_runtime_control_plane_all_modes,
    report_json,
    runtime_control_plane_report_json,
)
from services.evolution.longitudinal_evaluation import (
    EvolutionReleaseGate,
    decide_evolution_release,
    load_longitudinal_dataset,
    load_recorded_observation_bundle,
    run_longitudinal_evaluation,
)
from services.evolution.longitudinal_evaluation import (
    report_json as holdout_report_json,
)

_DEFAULT_HOLDOUT_DATASET = (
    Path(__file__).parents[1] / "services/evolution/evaluation/evolution_holdout_zh_v1.json"
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--runtime-control-plane",
        action="store_true",
        help="exercise the real evolution store/lifecycle/resolver with Chinese control cases",
    )
    parser.add_argument(
        "--holdout-results",
        type=Path,
        help=(
            "run the independent-evaluator holdout gate from a bounded JSON result bundle; "
            "no synthetic observations are generated by this command"
        ),
    )
    parser.add_argument(
        "--holdout-dataset",
        type=Path,
        default=_DEFAULT_HOLDOUT_DATASET,
        help="versioned Chinese holdout dataset",
    )
    parser.add_argument("--minimum-device-cases", type=int, default=2)
    parser.add_argument("--minimum-transfer-gain", type=float, default=0.0)
    args = parser.parse_args()
    exit_code = 0
    if args.holdout_results is not None:
        dataset = load_longitudinal_dataset(args.holdout_dataset)
        adapter = load_recorded_observation_bundle(
            args.holdout_results,
            dataset_version=dataset.version,
            dataset_sha256=dataset.manifest_sha256,
        )
        report = asyncio.run(run_longitudinal_evaluation(dataset, adapter))
        decision = decide_evolution_release(
            report,
            gate=EvolutionReleaseGate(
                minimum_device_cases=args.minimum_device_cases,
                minimum_transfer_gain=args.minimum_transfer_gain,
            ),
        )
        payload = json.dumps(
            {
                "report": json.loads(holdout_report_json(report)),
                "release_decision": {
                    "allowed": decision.allowed,
                    "reasons": list(decision.reasons),
                },
            },
            ensure_ascii=False,
            sort_keys=True,
            indent=2,
        )
        exit_code = 0 if decision.allowed else 2
    else:
        payload = (
            runtime_control_plane_report_json(evaluate_runtime_control_plane_all_modes())
            if args.runtime_control_plane
            else report_json(evaluate_all_modes(default_evolution_tasks()))
        )
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(payload + "\n", encoding="utf-8")
    print(payload)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
