"""Deterministic code generator for the Memoria multi-subject canonical contracts.

Single source of truth:
    packages/contracts/schemas/multi-subject/multi-subject.schema.json

The schema holds two independent contract families (ADR-0033 / PR-01):

- the canonical enums in ``$defs`` (frozen by ADR-0033 and later contract versions);
- the object contracts in ``objects`` (PR-01 / section 9.6): BindingManifest,
  RuntimeProfile + runtime-profile-v1 signed envelope, PolicyDecision /
  PolicyReceipt, SubjectResolution, MemoryEvent / MemoryWriteFence,
  NotificationIntent with NotificationFence / RelationshipSnapshot /
  RecipientSnapshot, SessionEvent / SessionEpochFence.

Outputs:
    python/multi_subject_contracts.py        (enums + Pydantic v2 models)
    apps/miniprogram/generated/multi-subject-contracts.js
                                                (CommonJS enums + lifecycle guards)

The generator is deterministic: it emits no timestamps, embeds the canonical
schema sha256 as ``source_hash``, iterates the schema in document order, and
fails on structural drift. Use ``--check`` in CI to prove regeneration produces
no diff.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NoReturn, cast

SCHEMA_REL_PATH = Path("packages/contracts/schemas/multi-subject/multi-subject.schema.json")
SCHEMA_ID = "memoria://contracts/multi-subject.schema.json"

# 与整改文档 PR-01/§4-§6/§8/§11.5 对齐的权威枚举集合。
# 顺序即输出顺序；对象合同不得再维护第二套内嵌 enum。
REQUIRED_ENUMS = (
    "DeviceDeclaredMode",
    "ServiceMode",
    "SubjectCategory",
    "AgeBand",
    "AgeEvidenceStatus",
    "BindingRole",
    "RelationshipType",
    "RelationshipStatus",
    "SpeakerState",
    "MemoryScope",
    "PolicyEffect",
    "PolicyObligation",
    "Capability",
    "Purpose",
    "DeviceTrust",
    "SafetyState",
    "DataClassification",
    "BindingStatus",
    "BindingReason",
    "IntentKind",
    "RecipientRole",
    "Channel",
    "TemplateKey",
    "ReasonCode",
    "IntentStatus",
    "RecipientStatus",
    "CancelReason",
    "ResolutionKind",
    "ConfirmationMethod",
    "MemoryEventType",
    "SessionEventType",
    "SharedMemoryProposalStatus",
    "SharedMemoryConfirmationDecision",
    "DeviceCertificateStatus",
    "DeviceLifecycleStatus",
    "DeviceCapability",
    "PhysicalMuteState",
    "PrivacyLightState",
    "SimLifecycleStatus",
    "OtaAssignmentStatus",
    "OtaBootStatus",
    "OtaSlotName",
    "RemoteDeviceCommandType",
)

# PR-01 / section 9.6 顶层对象合同（生成顺序即 schema objects.contracts 顺序）。
REQUIRED_OBJECT_CONTRACTS = (
    "BindingManifest",
    "RuntimeProfile",
    "RuntimeProfileSigned",
    "RuntimeProfileV2",
    "RuntimeProfileSignedV2",
    "PolicyDecision",
    "PolicyReceipt",
    "PolicyReceiptV2",
    "SubjectResolution",
    "MemoryWriteFence",
    "MemoryEvent",
    "SharedMemoryConfirmationEvidence",
    "SharedMemoryWithdrawalEvidence",
    "SharedMemoryProposal",
    "SharedMemoryPromotion",
    "NotificationFence",
    "RelationshipSnapshot",
    "RecipientSnapshot",
    "NotificationIntent",
    "DeviceAttestation",
    "OtaAssignment",
    "OtaStateReceipt",
    "RemoteDeviceCommand",
    "RemoteDeviceCommandExecution",
    "SessionEpochFence",
    "SessionEvent",
)

ALLOWED_MISSING_VALUE_POLICIES = ("fail_closed", "explicit")

# 安全关键顶层合同：生成 Go DecodeXStrict（DisallowUnknownFields + required key
# presence + Validate）。普通 json.Unmarshal 会忽略未知字段且无法区分
# required-nullable 的缺失，安全关键路径必须走严格解码。
REQUIRED_STRICT_DECODE = (
    "RuntimeProfileSigned",
    "RuntimeProfileSignedV2",
    "PolicyReceipt",
    "PolicyReceiptV2",
    "MemoryWriteFence",
    "SharedMemoryConfirmationEvidence",
    "SharedMemoryWithdrawalEvidence",
    "SharedMemoryProposal",
    "SharedMemoryPromotion",
    "NotificationFence",
    "DeviceAttestation",
    "OtaAssignment",
    "OtaStateReceipt",
    "RemoteDeviceCommand",
    "RemoteDeviceCommandExecution",
    "SessionEpochFence",
)

DEPRECATED_CONTRACT_REPLACEMENTS = {
    "RuntimeProfile": "RuntimeProfileV2",
    "RuntimeProfileSigned": "RuntimeProfileSignedV2",
    "PolicyReceipt": "PolicyReceiptV2",
}

OBJECT_DEFS_POINTER = "objects/properties/definitions/properties"
OBJECT_REF_PREFIX = f"#/{OBJECT_DEFS_POINTER}/"
CANONICAL_REF_PREFIX = "#/$defs/"

HEADER = (
    "Code generated by scripts/generate_multi_subject_contracts.py.\n"
    "Source: packages/contracts/schemas/multi-subject/multi-subject.schema.json\n"
    "DO NOT EDIT. Regenerate with: python scripts/generate_multi_subject_contracts.py"
)


def _fail(message: str) -> NoReturn:
    raise ValueError(f"multi-subject contract drift: {message}")


def load_schema(path: Path) -> dict[str, Any]:
    """Load and structurally validate the canonical schema."""
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("$id") != SCHEMA_ID:
        _fail(f"unexpected $id {data.get('$id')!r}")
    version = data.get("properties", {}).get("schema_version", {}).get("const")
    if not isinstance(version, int) or version < 1:
        _fail("schema_version must be a positive integer const")
    defs = data.get("$defs")
    if not isinstance(defs, dict):
        _fail("missing $defs")
    if tuple(defs.keys()) != REQUIRED_ENUMS:
        _fail(f"enum set/order drift: {tuple(defs.keys())} != {REQUIRED_ENUMS}")
    index = data.get("properties", {})
    for name in REQUIRED_ENUMS:
        if index.get(name, {}).get("$ref") != f"#/$defs/{name}":
            _fail(f"index property {name} must $ref #/$defs/{name}")
    for name, schema in defs.items():
        _validate_enum(name, schema)
    _validate_objects(data)
    return cast(dict[str, Any], data)


def _validate_enum(name: str, schema: dict[str, Any]) -> None:
    if schema.get("title") != name:
        _fail(f"{name}: title mismatch")
    if schema.get("type") != "string":
        _fail(f"{name}: type must be string")
    values = schema.get("enum")
    if not isinstance(values, list) or not values:
        _fail(f"{name}: enum must be a non-empty list")
    if len(set(values)) != len(values):
        _fail(f"{name}: duplicate enum values")
    if any(not isinstance(v, str) or not v for v in values):
        _fail(f"{name}: enum values must be non-empty strings")
    meta = schema.get("x-memoria")
    if not isinstance(meta, dict):
        _fail(f"{name}: missing x-memoria metadata")
    for key in ("contract_version", "frozen_by", "source", "missing_value_policy"):
        if key not in meta:
            _fail(f"{name}: x-memoria missing {key}")
    policy = meta["missing_value_policy"]
    if policy not in ALLOWED_MISSING_VALUE_POLICIES:
        _fail(f"{name}: unknown missing_value_policy {policy!r}")
    default = meta.get("default")
    if default is not None and default not in values:
        _fail(f"{name}: default {default!r} not in enum")
    notes = meta.get("value_notes")
    if not isinstance(notes, dict) or set(notes) != set(values):
        _fail(f"{name}: value_notes must cover exactly the enum values")
    for note in notes.values():
        if not isinstance(note, str) or not note or "\n" in note:
            _fail(f"{name}: value notes must be single-line non-empty strings")


def _resolve_ref(ref: str, object_defs: dict[str, Any], canonical: set[str]) -> tuple[str, str]:
    if ref.startswith(CANONICAL_REF_PREFIX):
        name = ref[len(CANONICAL_REF_PREFIX) :]
        if name not in canonical:
            _fail(f"unresolvable canonical $ref {ref}")
        return "canonical", name
    if ref.startswith(OBJECT_REF_PREFIX):
        name = ref[len(OBJECT_REF_PREFIX) :]
        if name not in object_defs:
            _fail(f"unresolvable object $ref {ref}")
        return "object", name
    _fail(f"unsupported $ref {ref}")


def _validate_field_schema(where: str, schema: dict[str, Any], object_defs: dict[str, Any], canonical: set[str]) -> None:
    if not isinstance(schema, dict):
        _fail(f"{where}: schema must be an object")
    if "$ref" in schema:
        _resolve_ref(schema["$ref"], object_defs, canonical)
        return
    if "enum" in schema:
        _fail(f"{where}: inline enum is forbidden; reference one canonical $defs enum")
    if "anyOf" in schema:
        branches = schema["anyOf"]
        if not isinstance(branches, list) or len(branches) != 2:
            _fail(f"{where}: anyOf must have exactly two branches (value + null)")
        for branch in branches:
            _validate_field_schema(f"{where}.anyOf", branch, object_defs, canonical)
        return
    json_type = schema.get("type")
    if isinstance(json_type, list):
        if json_type.count("null") != 1 or len(json_type) != 2:
            _fail(f"{where}: type list must be exactly [<type>, \"null\"]")
        json_type = json_type[0] if json_type[0] != "null" else json_type[1]
    if json_type == "null":
        return
    if json_type == "string":
        for key in ("minLength", "maxLength"):
            if key in schema and (not isinstance(schema[key], int) or schema[key] <= 0):
                _fail(f"{where}: {key} must be a positive integer")
        if "pattern" in schema and not isinstance(schema["pattern"], str):
            _fail(f"{where}: pattern must be a string")
        if "format" in schema and schema["format"] != "date-time":
            _fail(f"{where}: format must be date-time")
        if "const" in schema and not isinstance(schema["const"], str):
            _fail(f"{where}: string const must be a string")
    elif json_type in ("integer", "number"):
        for key in ("minimum", "maximum"):
            if key in schema and not isinstance(schema[key], (int, float)):
                _fail(f"{where}: {key} must be numeric")
        if "const" in schema and not isinstance(schema["const"], (int, float)):
            _fail(f"{where}: numeric const must be numeric")
    elif json_type == "boolean":
        if "const" in schema and not isinstance(schema["const"], bool):
            _fail(f"{where}: boolean const must be boolean")
    elif json_type == "array":
        items = schema.get("items")
        if not isinstance(items, dict):
            _fail(f"{where}: array items must be a schema")
        _validate_field_schema(f"{where}.items", items, object_defs, canonical)
        for key in ("minItems", "maxItems"):
            if key in schema and (not isinstance(schema[key], int) or schema[key] < 0):
                _fail(f"{where}: {key} must be a non-negative integer")
        if schema.get("minItems", 0) > schema.get("maxItems", sys.maxsize):
            _fail(f"{where}: minItems must not exceed maxItems")
    elif json_type == "object":
        if "maxProperties" in schema and (not isinstance(schema["maxProperties"], int) or schema["maxProperties"] <= 0):
            _fail(f"{where}: maxProperties must be a positive integer")
        addl = schema.get("additionalProperties")
        if isinstance(addl, dict):
            _validate_field_schema(f"{where}.additionalProperties", addl, object_defs, canonical)
        elif addl is not True:
            _fail(f"{where}: free-form object must set additionalProperties to a schema or true")
    else:
        _fail(f"{where}: unsupported type {json_type!r}")


def _validate_object_def(
    name: str,
    schema: dict[str, Any],
    object_defs: dict[str, Any],
    canonical: set[str],
) -> None:
    if schema.get("title") != name:
        _fail(f"objects.{name}: title mismatch")
    if not isinstance(schema.get("description"), str) or not schema["description"]:
        _fail(f"objects.{name}: missing description")
    if "enum" in schema:
        _fail(f"objects.{name}: object-local enum is forbidden; move it to canonical $defs")
    if "x-memoria-extends" in schema:
        base_name = schema["x-memoria-extends"]
        if not isinstance(base_name, str) or base_name not in object_defs:
            _fail(f"objects.{name}: x-memoria-extends must reference an existing definition")
        if base_name == name:
            _fail(f"objects.{name}: cannot extend itself")
        if schema.get("unevaluatedProperties") is not False:
            _fail(f"objects.{name}: extend contract must set unevaluatedProperties false")
        if schema.get("type") != "object":
            _fail(f"objects.{name}: extend contract type must be object")
        properties = schema.get("properties")
        if not isinstance(properties, dict) or not properties:
            _fail(f"objects.{name}: extend contract needs its own properties")
        required = schema.get("required")
        if not isinstance(required, list) or not required or any(p not in properties for p in required):
            _fail(f"objects.{name}: extend required must be a non-empty subset of properties")
        for pname, pschema in properties.items():
            _validate_field_schema(f"objects.{name}.{pname}", pschema, object_defs, canonical)
        _validate_object_invariants(name, schema, properties)
        return
    if schema.get("type") != "object":
        _fail(f"objects.{name}: type must be object")
    if schema.get("additionalProperties") is not False and schema.get("unevaluatedProperties") is not False:
        _fail(f"objects.{name}: additionalProperties/unevaluatedProperties must be false")
    properties = schema.get("properties")
    if not isinstance(properties, dict) or not properties:
        _fail(f"objects.{name}: missing properties")
    required = schema.get("required")
    if not isinstance(required, list) or not required or any(p not in properties for p in required):
        _fail(f"objects.{name}: required must be a non-empty subset of properties")
    for pname, pschema in properties.items():
        _validate_field_schema(f"objects.{name}.{pname}", pschema, object_defs, canonical)
    _validate_object_invariants(name, schema, properties)


def _validate_object_invariants(
    name: str, schema: dict[str, Any], properties: dict[str, Any]
) -> None:
    """Validate the declarative cross-field subset emitted in every language."""

    def field(value: object, where: str) -> str:
        if not isinstance(value, str) or value not in properties:
            _fail(f"objects.{name}.{where}: unknown field {value!r}")
        return value

    def path(value: object, where: str) -> str:
        if not isinstance(value, str) or not value:
            _fail(f"objects.{name}.{where}: path must be a non-empty string")
        root = value.split(".", 1)[0]
        if root not in properties:
            _fail(f"objects.{name}.{where}: unknown root field {root!r}")
        return value

    def when(rule: object, where: str) -> None:
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.{where}: when must be an object")
        path(rule.get("path"), f"{where}.path")
        operators = {"equals", "not_equals", "in", "not_in"} & set(rule)
        if len(operators) != 1:
            _fail(f"objects.{name}.{where}: when needs exactly one operator")
        for operator in ("in", "not_in"):
            if operator in rule and (not isinstance(rule[operator], list) or not rule[operator]):
                _fail(f"objects.{name}.{where}.{operator}: expected non-empty list")

    for index, pair in enumerate(schema.get("x-memoria-paired-arrays", [])):
        if not isinstance(pair, list) or len(pair) != 2:
            _fail(f"objects.{name}.x-memoria-paired-arrays[{index}] must contain two fields")
        field(pair[0], "x-memoria-paired-arrays")
        field(pair[1], "x-memoria-paired-arrays")
    for index, rule in enumerate(schema.get("x-memoria-value-pairs", [])):
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.x-memoria-value-pairs[{index}] must be an object")
        field(rule.get("left_field"), "x-memoria-value-pairs.left_field")
        field(rule.get("right_field"), "x-memoria-value-pairs.right_field")
        pairs = rule.get("pairs")
        if not isinstance(pairs, dict) or not pairs or any(
            not isinstance(key, str) or not isinstance(value, str)
            for key, value in pairs.items()
        ):
            _fail(f"objects.{name}.x-memoria-value-pairs[{index}].pairs invalid")
        if not isinstance(rule.get("bidirectional"), bool):
            _fail(f"objects.{name}.x-memoria-value-pairs[{index}].bidirectional must be bool")
    for index, rule in enumerate(schema.get("x-memoria-non-null-if", [])):
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.x-memoria-non-null-if[{index}] must be an object")
        field(rule.get("field"), "x-memoria-non-null-if.field")
        values = rule.get("non_null_fields")
        if not isinstance(values, list) or not values:
            _fail(f"objects.{name}.x-memoria-non-null-if[{index}] needs fields")
        for value in values:
            field(value, "x-memoria-non-null-if.non_null_fields")
    for index, pair in enumerate(schema.get("x-memoria-distinct-fields", [])):
        if not isinstance(pair, list) or len(pair) != 2:
            _fail(f"objects.{name}.x-memoria-distinct-fields[{index}] must contain two fields")
        field(pair[0], "x-memoria-distinct-fields")
        field(pair[1], "x-memoria-distinct-fields")
    approval = schema.get("x-memoria-approval-subjects")
    if approval is not None:
        if not isinstance(approval, dict):
            _fail(f"objects.{name}.x-memoria-approval-subjects must be an object")
        for key in ("proposer_field", "co_subjects_field", "required_field"):
            field(approval.get(key), f"x-memoria-approval-subjects.{key}")
    coverage = schema.get("x-memoria-confirmation-coverage")
    if coverage is not None:
        if not isinstance(coverage, dict):
            _fail(f"objects.{name}.x-memoria-confirmation-coverage must be an object")
        for key in ("required_subject_ids_field", "evidence_field"):
            field(coverage.get(key), f"x-memoria-confirmation-coverage.{key}")
    epoch = schema.get("x-memoria-epoch-semantics")
    if epoch is not None:
        if not isinstance(epoch, dict):
            _fail(f"objects.{name}.x-memoria-epoch-semantics must be an object")
        field(epoch.get("epoch_field"), "x-memoria-epoch-semantics.epoch_field")
        for key in ("zero_null_fields", "positive_non_null_fields"):
            values = epoch.get(key)
            if not isinstance(values, list):
                _fail(f"objects.{name}.x-memoria-epoch-semantics.{key} must be a list")
            for value in values:
                field(value, f"x-memoria-epoch-semantics.{key}")
    for key in ("x-memoria-forbidden-values", "x-memoria-unique-by"):
        rules = schema.get(key, [])
        if not isinstance(rules, list):
            _fail(f"objects.{name}.{key} must be a list")
        for rule in rules:
            if not isinstance(rule, dict):
                _fail(f"objects.{name}.{key} entries must be objects")
            field(rule.get("field"), f"{key}.field")
    for index, rule in enumerate(schema.get("x-memoria-conditional-fields", [])):
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.x-memoria-conditional-fields[{index}] must be an object")
        when(rule.get("when"), f"x-memoria-conditional-fields[{index}].when")
        for key in ("require_non_null", "require_null", "require_non_empty", "require_empty"):
            values = rule.get(key, [])
            if not isinstance(values, list):
                _fail(f"objects.{name}.x-memoria-conditional-fields[{index}].{key} must be a list")
            for value in values:
                path(value, f"x-memoria-conditional-fields[{index}].{key}")
        for key in ("require_equals", "require_in", "forbid_contains"):
            values = rule.get(key, {})
            if not isinstance(values, dict):
                _fail(f"objects.{name}.x-memoria-conditional-fields[{index}].{key} must be an object")
            for value in values:
                path(value, f"x-memoria-conditional-fields[{index}].{key}")
    for key in ("x-memoria-equal-paths", "x-memoria-set-equal-paths"):
        entries = schema.get(key, [])
        if not isinstance(entries, list):
            _fail(f"objects.{name}.{key} must be a list")
        for index, entry in enumerate(entries):
            paths = entry if isinstance(entry, list) else entry.get("paths") if isinstance(entry, dict) else None
            if not isinstance(paths, list) or len(paths) < 2:
                _fail(f"objects.{name}.{key}[{index}] needs at least two paths")
            for value in paths:
                path(value, f"{key}[{index}]")
            if isinstance(entry, dict) and "when" in entry:
                when(entry["when"], f"{key}[{index}].when")
    for index, rule in enumerate(schema.get("x-memoria-record-set-equals", [])):
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.x-memoria-record-set-equals[{index}] must be an object")
        path(rule.get("left_path"), f"x-memoria-record-set-equals[{index}].left_path")
        path(rule.get("right_path"), f"x-memoria-record-set-equals[{index}].right_path")
        left_fields = rule.get("left_fields")
        right_fields = rule.get("right_fields")
        if not isinstance(left_fields, list) or not isinstance(right_fields, list) or len(left_fields) != len(right_fields) or not left_fields:
            _fail(f"objects.{name}.x-memoria-record-set-equals[{index}] field mappings invalid")
    for index, rule in enumerate(schema.get("x-memoria-record-coverage", [])):
        if not isinstance(rule, dict):
            _fail(f"objects.{name}.x-memoria-record-coverage[{index}] must be an object")
        path(rule.get("required_ids_path"), f"x-memoria-record-coverage[{index}].required_ids_path")
        path(rule.get("records_path"), f"x-memoria-record-coverage[{index}].records_path")
        if not isinstance(rule.get("record_id_field"), str):
            _fail(f"objects.{name}.x-memoria-record-coverage[{index}].record_id_field invalid")
        if "when" in rule:
            when(rule["when"], f"x-memoria-record-coverage[{index}].when")
    for index, rule in enumerate(schema.get("x-memoria-time-order", [])):
        if not isinstance(rule, dict) or not isinstance(rule.get("strict"), bool):
            _fail(f"objects.{name}.x-memoria-time-order[{index}] invalid")
        path(rule.get("earlier_path"), f"x-memoria-time-order[{index}].earlier_path")
        path(rule.get("later_path"), f"x-memoria-time-order[{index}].later_path")
        if "when" in rule:
            when(rule["when"], f"x-memoria-time-order[{index}].when")
    for index, rule in enumerate(schema.get("x-memoria-integer-order", [])):
        if not isinstance(rule, dict) or rule.get("operator") not in (">=", ">", "=="):
            _fail(f"objects.{name}.x-memoria-integer-order[{index}] invalid")
        path(rule.get("left_path"), f"x-memoria-integer-order[{index}].left_path")
        path(rule.get("right_path"), f"x-memoria-integer-order[{index}].right_path")
    for index, rule in enumerate(schema.get("x-memoria-selected-record-integer-order", [])):
        if not isinstance(rule, dict) or rule.get("operator") not in (">=", "<=", ">", "<", "=="):
            _fail(f"objects.{name}.x-memoria-selected-record-integer-order[{index}] invalid")
        for key in ("selector_path", "records_path", "other_path"):
            path(rule.get(key), f"x-memoria-selected-record-integer-order[{index}].{key}")
        for key in ("record_selector_field", "record_value_field"):
            if not isinstance(rule.get(key), str) or not rule[key]:
                _fail(f"objects.{name}.x-memoria-selected-record-integer-order[{index}].{key} invalid")
    for index, rule in enumerate(schema.get("x-memoria-requires-capability", [])):
        if not isinstance(rule, dict) or not isinstance(rule.get("state_values"), list) or not isinstance(rule.get("capability"), str):
            _fail(f"objects.{name}.x-memoria-requires-capability[{index}] invalid")
        path(rule.get("state_path"), f"x-memoria-requires-capability[{index}].state_path")
        path(rule.get("capabilities_path"), f"x-memoria-requires-capability[{index}].capabilities_path")
    for index, paths in enumerate(schema.get("x-memoria-subset-paths", [])):
        if not isinstance(paths, list) or len(paths) != 2:
            _fail(f"objects.{name}.x-memoria-subset-paths[{index}] invalid")
        path(paths[0], f"x-memoria-subset-paths[{index}]")
        path(paths[1], f"x-memoria-subset-paths[{index}]")
    for index, rule in enumerate(schema.get("x-memoria-sorted-unique-by", [])):
        if not isinstance(rule, dict) or not isinstance(rule.get("item_field"), str):
            _fail(f"objects.{name}.x-memoria-sorted-unique-by[{index}] invalid")
        field(rule.get("field"), f"x-memoria-sorted-unique-by[{index}].field")
    required_values = schema.get("x-memoria-required-values", {})
    if not isinstance(required_values, dict):
        _fail(f"objects.{name}.x-memoria-required-values must be an object")
    for value in required_values:
        path(value, "x-memoria-required-values")
    context_inputs = schema.get("x-memoria-context-hash-inputs", [])
    if not isinstance(context_inputs, list):
        _fail(f"objects.{name}.x-memoria-context-hash-inputs must be a list")
    for value in context_inputs:
        path(value, "x-memoria-context-hash-inputs")

    supported = {
        "x-memoria-extends",
        "x-memoria-paired-arrays",
        "x-memoria-value-pairs",
        "x-memoria-non-null-if",
        "x-memoria-distinct-fields",
        "x-memoria-approval-subjects",
        "x-memoria-confirmation-coverage",
        "x-memoria-epoch-semantics",
        "x-memoria-forbidden-values",
        "x-memoria-unique-by",
        "x-memoria-conditional-fields",
        "x-memoria-equal-paths",
        "x-memoria-set-equal-paths",
        "x-memoria-record-set-equals",
        "x-memoria-record-coverage",
        "x-memoria-time-order",
        "x-memoria-integer-order",
        "x-memoria-selected-record-integer-order",
        "x-memoria-requires-capability",
        "x-memoria-subset-paths",
        "x-memoria-sorted-unique-by",
        "x-memoria-required-values",
        "x-memoria-context-hash-inputs",
        "x-memoria-contract-status",
    }
    unknown = {key for key in schema if key.startswith("x-memoria-")} - supported
    if unknown:
        _fail(f"objects.{name}: unsupported invariant metadata {sorted(unknown)}")


def _validate_objects(data: dict[str, Any]) -> dict[str, dict[str, Any]]:
    objects = data.get("objects")
    if not isinstance(objects, dict):
        _fail("missing objects section")
    props = objects.get("properties")
    if not isinstance(props, dict):
        _fail("objects.properties missing")
    version = props.get("objects_version", {}).get("const")
    if not isinstance(version, int) or version < 1:
        _fail("objects_version must be a positive integer const")
    defs_section = props.get("definitions")
    if not isinstance(defs_section, dict):
        _fail("objects.definitions must be an object")
    defs = defs_section.get("properties")
    if not isinstance(defs, dict) or not defs:
        _fail("objects.definitions must be a non-empty object")
    contracts = props.get("contracts", {}).get("const")
    if not isinstance(contracts, list) or any(not isinstance(entry, dict) for entry in contracts):
        _fail("objects.contracts must be a lifecycle record list")
    contract_names = tuple(entry.get("name") for entry in contracts)
    if contract_names != REQUIRED_OBJECT_CONTRACTS:
        _fail(f"objects.contracts drift: {contract_names!r} != {REQUIRED_OBJECT_CONTRACTS}")
    lifecycle_keys = {"name", "lifecycle", "consumer_mode", "new_producer", "replacement"}
    forbidden: dict[str, str] = {}
    for entry in contracts:
        if set(entry) != lifecycle_keys:
            _fail(f"objects.contracts.{entry.get('name')}: lifecycle keys drift")
        name = entry["name"]
        if entry["lifecycle"] == "current":
            if entry != {
                "name": name,
                "lifecycle": "current",
                "consumer_mode": "canonical",
                "new_producer": "allowed",
                "replacement": None,
            }:
                _fail(f"objects.contracts.{name}: current contract lifecycle invalid")
        elif entry["lifecycle"] == "deprecated":
            replacement = entry.get("replacement")
            if (
                entry.get("consumer_mode") != "migration_only"
                or entry.get("new_producer") != "forbidden"
                or not isinstance(replacement, str)
                or replacement not in REQUIRED_OBJECT_CONTRACTS
            ):
                _fail(f"objects.contracts.{name}: deprecated contract lifecycle invalid")
            forbidden[name] = replacement
        else:
            _fail(f"objects.contracts.{name}: unknown lifecycle")
    if forbidden != DEPRECATED_CONTRACT_REPLACEMENTS:
        _fail(
            "objects.contracts deprecated producer set drift: "
            f"{forbidden!r} != {DEPRECATED_CONTRACT_REPLACEMENTS!r}"
        )
    canonical = set(data.get("$defs", {}))
    for name in REQUIRED_OBJECT_CONTRACTS:
        if name not in defs:
            _fail(f"objects.contracts references missing definition {name}")
    for name, schema in defs.items():
        _validate_object_def(name, schema, defs, canonical)
    for name, schema in defs.items():
        base_name = schema.get("x-memoria-extends")
        if not isinstance(base_name, str):
            continue
        base = defs[base_name]
        base_props = set(base.get("properties", {}))
        own_props = set(schema.get("properties", {}))
        if not base_props <= own_props:
            _fail(f"objects.{name}: must be a strict superset of {base_name} fields")
        base_required = set(base.get("required", []))
        own_required = set(schema.get("required", []))
        if not base_required <= own_required:
            _fail(f"objects.{name}: required must cover {base_name} required fields")
    return defs


def _contract_lifecycle(data: dict[str, Any]) -> tuple[dict[str, Any], ...]:
    entries = data["objects"]["properties"]["contracts"]["const"]
    return tuple(cast(list[dict[str, Any]], entries))


def _screaming(name: str) -> str:
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).upper()


def _commonjs_key(name: str, value: str) -> str:
    """Return the stable Mini Program property spelling used by existing consumers."""
    parts = [part for part in value.split("_") if part]
    key = "".join(part[:1].upper() + part[1:].lower() for part in parts)
    if key and key[0].isdigit():
        # Preserve the pre-codegen Mini Program spelling for AgeBand's ``14_17``.
        return f"Age{value}"
    if not key:
        _fail(f"{name}: cannot derive CommonJS key from {value!r}")
    return key


def _one_line(value: str) -> str:
    return " ".join(value.split())


def _meta_of(schema: dict[str, Any]) -> dict[str, Any]:
    meta = schema["x-memoria"]
    if not isinstance(meta, dict):
        _fail("x-memoria metadata must be an object")
    return meta


# ---------------------------------------------------------------------------
# Field model shared by all language emitters
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FieldSpec:
    name: str
    json_type: str  # string | integer | number | boolean | array | object | enum | ref
    ref_kind: str | None  # canonical | object
    ref_name: str | None
    enum_values: tuple[str, ...] | None
    has_const: bool
    const_value: str | int | bool | None
    nullable: bool
    required: bool
    min_length: int | None
    max_length: int | None
    pattern: str | None
    format: str | None
    minimum: float | None
    maximum: float | None
    min_items: int | None
    max_items: int | None
    max_properties: int | None
    item_ref_kind: str | None
    item_ref_name: str | None
    item_json_type: str | None
    item_min_length: int | None
    item_max_length: int | None
    additional_properties: str | None
    unique_items: bool
    value_schema: dict[str, Any]


def _field_spec(
    name: str,
    schema: dict[str, Any],
    *,
    required: bool,
    object_defs: dict[str, Any],
    canonical: set[str],
) -> FieldSpec:
    base = dict(schema)
    nullable = False
    if "anyOf" in base:
        branches = base["anyOf"]
        non_null = [b for b in branches if b.get("type") != "null"]
        if len(non_null) != 1 or len(branches) != 2:
            _fail(f"objects.{name}: anyOf must be value + null")
        base = dict(non_null[0])
        nullable = True
    if isinstance(base.get("type"), list):
        types = base["type"]
        if types.count("null") != 1 or len(types) != 2:
            _fail(f"objects.{name}: type list must be [<type>, \"null\"]")
        nullable = True
        base = dict(base)
        base["type"] = types[0] if types[0] != "null" else types[1]
    ref_kind = ref_name = None
    enum_values: tuple[str, ...] | None = None
    json_type: str
    if "$ref" in base:
        ref_kind, ref_name = _resolve_ref(base["$ref"], object_defs, canonical)
        json_type = "ref"
    elif "enum" in base:
        enum_values = tuple(base["enum"])
        json_type = "enum"
    else:
        raw_json_type = base.get("type")
        if not isinstance(raw_json_type, str):
            _fail(f"objects.{name}: missing type")
        json_type = raw_json_type

    item_kind = item_name = item_primitive = None
    items = base.get("items", {}) if json_type == "array" else {}
    if isinstance(items, dict) and "$ref" in items:
        item_kind, item_name = _resolve_ref(items["$ref"], object_defs, canonical)
    elif isinstance(items, dict) and "enum" in items:
        item_kind = "enum"
    elif isinstance(items, dict):
        item_primitive = items.get("type")

    addl = base.get("additionalProperties") if json_type == "object" else None
    addl_kind = "string" if isinstance(addl, dict) and addl.get("type") == "string" else None
    return FieldSpec(
        name=name,
        json_type=json_type,
        ref_kind=ref_kind,
        ref_name=ref_name,
        enum_values=enum_values,
        has_const="const" in base,
        const_value=base.get("const"),
        nullable=nullable,
        required=required,
        min_length=base.get("minLength"),
        max_length=base.get("maxLength"),
        pattern=base.get("pattern"),
        format=base.get("format"),
        minimum=base.get("minimum"),
        maximum=base.get("maximum"),
        min_items=base.get("minItems"),
        max_items=base.get("maxItems"),
        max_properties=base.get("maxProperties"),
        item_ref_kind=item_kind,
        item_ref_name=item_name,
        item_json_type=item_primitive if isinstance(item_primitive, str) else None,
        item_min_length=items.get("minLength") if isinstance(items, dict) else None,
        item_max_length=items.get("maxLength") if isinstance(items, dict) else None,
        additional_properties=addl_kind,
        unique_items=bool(base.get("uniqueItems")),
        value_schema=base,
    )


def _object_fields(name: str, schema: dict[str, Any], object_defs: dict[str, Any], canonical: set[str]) -> list[FieldSpec]:
    required = set(schema.get("required", []))
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        _fail(f"objects.{name}: missing properties")
    return [
        _field_spec(pname, pschema, required=pname in required, object_defs=object_defs, canonical=canonical)
        for pname, pschema in properties.items()
    ]


def _definition_kind(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return "enum"
    if "x-memoria-extends" in schema:
        return "extend"
    return "object"


def _normalized_invariants(schema: dict[str, Any]) -> list[dict[str, Any]]:
    """Normalize canonical x-memoria rules for every generated validator.

    The returned JSON-compatible list is the single cross-language rule DSL.
    Python, TypeScript, Go and the firmware compact artifact all receive these
    exact rules, so a cross-field constraint cannot silently exist in only one
    language.
    """

    rules: list[dict[str, Any]] = []
    for left, right in schema.get("x-memoria-paired-arrays", []):
        rules.append({"kind": "paired_arrays", "left_path": left, "right_path": right})
    for rule in schema.get("x-memoria-value-pairs", []):
        rules.append({"kind": "value_pairs", **rule})
    for rule in schema.get("x-memoria-non-null-if", []):
        rules.append(
            {
                "kind": "conditional",
                "when": {"path": rule["field"], "equals": rule["equals"]},
                "require_non_null": list(rule["non_null_fields"]),
            }
        )
    for pair in schema.get("x-memoria-distinct-fields", []):
        rules.append({"kind": "distinct", "paths": list(pair)})
    approval = schema.get("x-memoria-approval-subjects")
    if isinstance(approval, dict):
        rules.append({"kind": "approval_subjects", **approval})
    coverage = schema.get("x-memoria-confirmation-coverage")
    if isinstance(coverage, dict):
        rules.append({"kind": "confirmation_coverage", **coverage})
    epoch = schema.get("x-memoria-epoch-semantics")
    if isinstance(epoch, dict):
        rules.append({"kind": "epoch_semantics", **epoch})
    for rule in schema.get("x-memoria-forbidden-values", []):
        rules.append({"kind": "forbidden_values", **rule})
    for rule in schema.get("x-memoria-unique-by", []):
        rules.append({"kind": "unique_by", **rule})
    for rule in schema.get("x-memoria-conditional-fields", []):
        rules.append({"kind": "conditional", **rule})
    for entry in schema.get("x-memoria-equal-paths", []):
        if isinstance(entry, list):
            rules.append({"kind": "equal", "paths": entry})
        else:
            rules.append({"kind": "equal", **entry})
    for paths in schema.get("x-memoria-set-equal-paths", []):
        rules.append({"kind": "set_equal", "paths": paths})
    for rule in schema.get("x-memoria-record-set-equals", []):
        rules.append({"kind": "record_set_equal", **rule})
    for rule in schema.get("x-memoria-record-coverage", []):
        rules.append({"kind": "record_coverage", **rule})
    for rule in schema.get("x-memoria-time-order", []):
        rules.append({"kind": "time_order", **rule})
    for rule in schema.get("x-memoria-integer-order", []):
        rules.append({"kind": "integer_order", **rule})
    for rule in schema.get("x-memoria-selected-record-integer-order", []):
        rules.append({"kind": "selected_record_integer_order", **rule})
    for rule in schema.get("x-memoria-requires-capability", []):
        rules.append({"kind": "requires_capability", **rule})
    for paths in schema.get("x-memoria-subset-paths", []):
        rules.append({"kind": "subset", "subset_path": paths[0], "superset_path": paths[1]})
    for rule in schema.get("x-memoria-sorted-unique-by", []):
        rules.append({"kind": "sorted_unique_by", **rule})
    required_values = schema.get("x-memoria-required-values")
    if isinstance(required_values, dict):
        rules.append({"kind": "required_values", "values": required_values})
    return rules


# ---------------------------------------------------------------------------
# Python (Pydantic v2)
# ---------------------------------------------------------------------------


def _generate_python(
    defs: dict[str, dict[str, Any]],
    object_defs: dict[str, dict[str, Any]],
    contract_lifecycle: tuple[dict[str, Any], ...],
    schema_version: int,
    objects_version: int,
    schema_hash: str,
) -> str:
    lines: list[str] = []
    lines.append('"""Memoria multi-subject canonical contracts (ADR-0033 / PR-01).')
    lines.append("")
    for header_line in HEADER.splitlines():
        lines.append(header_line)
    lines.append(f"Source hash: sha256:{schema_hash}")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import enum")
    lines.append("import json")
    lines.append("import re")
    lines.append("from datetime import datetime")
    lines.append("from typing import Annotated, Any, Literal, Self")
    lines.append("")
    lines.append("from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator, model_validator")
    lines.append("")
    lines.append(f"CONTRACTS_SCHEMA_VERSION: int = {schema_version}")
    lines.append("")
    lines.append(
        'RFC3339_STRICT_PATTERN = re.compile(r"^\\d{4}-\\d{2}-\\d{2}[Tt]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:[Zz]|[+-](?:[01]\\d|2[0-3]):[0-5]\\d)$")'
    )
    lines.append("")
    lines.append("def _unique_json_items(value: tuple[object, ...]) -> bool:")
    lines.append("    keys = [json.dumps(item, ensure_ascii=False, sort_keys=True, separators=(\",\", \":\"), default=str) for item in value]")
    lines.append("    return len(keys) == len(set(keys))")
    lines.append("")
    lines.extend(
        '''_PATH_MISSING = object()

def _path_get(payload: object, path: str) -> object:
    current = payload
    for part in path.split("."):
        if not isinstance(current, dict) or part not in current:
            return _PATH_MISSING
        current = current[part]
    return current

def _stable_contract_key(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))

def _rule_matches(payload: dict[str, object], when: Any) -> bool:
    if not isinstance(when, dict):
        return True
    value = _path_get(payload, str(when["path"]))
    if "equals" in when:
        return bool(value == when["equals"])
    if "not_equals" in when:
        return bool(value != when["not_equals"])
    if "in" in when:
        return value in when["in"]
    if "not_in" in when:
        return value not in when["not_in"]
    return False

def _contract_datetime(value: object, path: str) -> datetime:
    if not isinstance(value, str):
        raise ValueError(f"{path}: expected RFC3339 string")
    return datetime.fromisoformat(value.replace("Z", "+00:00").replace("z", "+00:00"))

def _validate_contract_invariants(name: str, payload: dict[str, object], rules: tuple[dict[str, Any], ...]) -> None:
    for rule in rules:
        kind = rule["kind"]
        when = rule.get("when")
        if not _rule_matches(payload, when):
            continue
        if kind == "paired_arrays":
            left = _path_get(payload, str(rule["left_path"]))
            right = _path_get(payload, str(rule["right_path"]))
            if not isinstance(left, list) or not isinstance(right, list) or len(left) != len(right):
                raise ValueError(f"{name}: paired arrays must have equal length")
        elif kind == "value_pairs":
            left = _path_get(payload, str(rule["left_field"]))
            right = _path_get(payload, str(rule["right_field"]))
            pairs = rule["pairs"]
            if not isinstance(pairs, dict):
                raise ValueError(f"{name}: invalid value-pair rule")
            if left in pairs and right != pairs[left]:
                raise ValueError(f"{name}: restricted authority pair mismatch")
            if rule.get("bidirectional") and right in pairs.values():
                inverse = {value: key for key, value in pairs.items()}
                if left != inverse[right]:
                    raise ValueError(f"{name}: restricted authority pair mismatch")
        elif kind == "conditional":
            for path in rule.get("require_non_null", []):
                if _path_get(payload, str(path)) in (None, _PATH_MISSING):
                    raise ValueError(f"{name}.{path}: condition requires non-null")
            for path in rule.get("require_null", []):
                if _path_get(payload, str(path)) is not None:
                    raise ValueError(f"{name}.{path}: condition requires null")
            for path in rule.get("require_non_empty", []):
                value = _path_get(payload, str(path))
                if value in (None, _PATH_MISSING, "", [], {}):
                    raise ValueError(f"{name}.{path}: condition requires non-empty")
            for path in rule.get("require_empty", []):
                if _path_get(payload, str(path)) not in ([], {}, ""):
                    raise ValueError(f"{name}.{path}: condition requires empty")
            equals = rule.get("require_equals", {})
            if isinstance(equals, dict):
                for path, expected in equals.items():
                    if _path_get(payload, path) != expected:
                        raise ValueError(f"{name}.{path}: condition requires exact value")
            allowed = rule.get("require_in", {})
            if isinstance(allowed, dict):
                for path, values in allowed.items():
                    if _path_get(payload, path) not in values:
                        raise ValueError(f"{name}.{path}: condition rejects value")
            forbidden = rule.get("forbid_contains", {})
            if isinstance(forbidden, dict):
                for path, values in forbidden.items():
                    actual = _path_get(payload, path)
                    if isinstance(actual, list) and any(value in actual for value in values):
                        raise ValueError(f"{name}.{path}: condition forbids capability")
        elif kind in ("equal", "distinct"):
            paths = rule["paths"]
            values = [_path_get(payload, str(path)) for path in paths]
            keys = [_stable_contract_key(value) for value in values]
            if kind == "equal" and len(set(keys)) != 1:
                raise ValueError(f"{name}: exact fence paths differ")
            if kind == "distinct" and len(set(keys)) != len(keys):
                raise ValueError(f"{name}: authority values must be distinct")
        elif kind == "set_equal":
            paths = rule["paths"]
            values = [_path_get(payload, str(path)) for path in paths]
            if any(not isinstance(value, list) for value in values):
                raise ValueError(f"{name}: set-equality paths must be arrays")
            sets = [{_stable_contract_key(item) for item in value} for value in values if isinstance(value, list)]
            if not sets or any(value != sets[0] for value in sets[1:]):
                raise ValueError(f"{name}: exact subject/evidence set differs")
        elif kind == "record_set_equal":
            left = _path_get(payload, str(rule["left_path"]))
            right = _path_get(payload, str(rule["right_path"]))
            if not isinstance(left, list) or not isinstance(right, list):
                raise ValueError(f"{name}: record-set paths must be arrays")
            left_fields = rule["left_fields"]
            right_fields = rule["right_fields"]
            left_keys = {_stable_contract_key([item[field] for field in left_fields]) for item in left if isinstance(item, dict)}
            right_keys = {_stable_contract_key([item[field] for field in right_fields]) for item in right if isinstance(item, dict)}
            if len(left_keys) != len(left) or len(right_keys) != len(right) or left_keys != right_keys:
                raise ValueError(f"{name}: approval snapshot revisions/hashes differ")
        elif kind == "record_coverage":
            required = _path_get(payload, str(rule["required_ids_path"]))
            records = _path_get(payload, str(rule["records_path"]))
            if not isinstance(required, list) or not isinstance(records, list):
                raise ValueError(f"{name}: record coverage requires arrays")
            ids = [item[rule["record_id_field"]] for item in records if isinstance(item, dict)]
            if len(ids) != len(records) or len(ids) != len(set(ids)) or set(ids) != set(required):
                raise ValueError(f"{name}: record coverage is incomplete")
        elif kind == "time_order":
            earlier = _contract_datetime(_path_get(payload, str(rule["earlier_path"])), str(rule["earlier_path"]))
            later = _contract_datetime(_path_get(payload, str(rule["later_path"])), str(rule["later_path"]))
            if earlier > later or (rule.get("strict") and earlier == later):
                raise ValueError(f"{name}: fence time window is expired or unbounded")
        elif kind == "integer_order":
            left = _path_get(payload, str(rule["left_path"]))
            right = _path_get(payload, str(rule["right_path"]))
            if not isinstance(left, int) or isinstance(left, bool) or not isinstance(right, int) or isinstance(right, bool):
                raise ValueError(f"{name}: integer-order fields are invalid")
            operator = rule["operator"]
            if (operator == ">=" and left < right) or (operator == ">" and left <= right) or (operator == "==" and left != right):
                raise ValueError(f"{name}: monotonic integer fence failed")
        elif kind == "selected_record_integer_order":
            selector = _path_get(payload, str(rule["selector_path"]))
            records = _path_get(payload, str(rule["records_path"]))
            other = _path_get(payload, str(rule["other_path"]))
            if not isinstance(records, list) or not isinstance(other, int) or isinstance(other, bool):
                raise ValueError(f"{name}: selected record integer fence is invalid")
            matches = [item for item in records if isinstance(item, dict) and item.get(rule["record_selector_field"]) == selector]
            if len(matches) != 1:
                raise ValueError(f"{name}: selected record must exist exactly once")
            selected = matches[0].get(rule["record_value_field"])
            if not isinstance(selected, int) or isinstance(selected, bool):
                raise ValueError(f"{name}: selected record security version is absent")
            operator = rule["operator"]
            if ((operator == ">=" and selected < other) or (operator == "<=" and selected > other) or (operator == ">" and selected <= other) or (operator == "<" and selected >= other) or (operator == "==" and selected != other)):
                raise ValueError(f"{name}: selected record violates monotonic security order")
        elif kind == "required_values":
            values = rule["values"]
            if not isinstance(values, dict) or any(_path_get(payload, path) != expected for path, expected in values.items()):
                raise ValueError(f"{name}: required trusted state is absent")
        elif kind == "requires_capability":
            state = _path_get(payload, str(rule["state_path"]))
            capabilities = _path_get(payload, str(rule["capabilities_path"]))
            if state in rule["state_values"] and (not isinstance(capabilities, list) or rule["capability"] not in capabilities):
                raise ValueError(f"{name}: hardware state lacks declared capability")
        elif kind == "subset":
            subset = _path_get(payload, str(rule["subset_path"]))
            superset = _path_get(payload, str(rule["superset_path"]))
            if not isinstance(subset, list) or not isinstance(superset, list) or not set(subset) <= set(superset):
                raise ValueError(f"{name}: attested capabilities must be a declared subset")
        elif kind in ("unique_by", "sorted_unique_by"):
            items = _path_get(payload, str(rule["field"]))
            if not isinstance(items, list):
                raise ValueError(f"{name}: unique-by path must be an array")
            keys = [item[rule["item_field"]] for item in items if isinstance(item, dict)]
            if len(keys) != len(items) or len(keys) != len(set(keys)):
                raise ValueError(f"{name}: record key must be unique")
            if kind == "sorted_unique_by" and keys != sorted(keys):
                raise ValueError(f"{name}: records must use canonical sorted order")
        elif kind == "forbidden_values":
            if _path_get(payload, str(rule["field"])) in rule["values"]:
                raise ValueError(f"{name}: forbidden fail-closed value")
        elif kind == "approval_subjects":
            proposer = _path_get(payload, str(rule["proposer_field"]))
            co_subjects = _path_get(payload, str(rule["co_subjects_field"]))
            required = _path_get(payload, str(rule["required_field"]))
            if not isinstance(co_subjects, list) or not isinstance(required, list) or set(required) != {proposer, *co_subjects} or len(required) != len(set(required)):
                raise ValueError(f"{name}: required approvals must equal proposer plus co-subjects")
        elif kind == "confirmation_coverage":
            required = _path_get(payload, str(rule["required_subject_ids_field"]))
            evidence = _path_get(payload, str(rule["evidence_field"]))
            if not isinstance(required, list) or not isinstance(evidence, list):
                raise ValueError(f"{name}: confirmation coverage requires arrays")
            subjects = [item[rule["evidence_subject_field"]] for item in evidence if isinstance(item, dict)]
            if len(subjects) != len(evidence) or len(subjects) != len(set(subjects)) or set(subjects) != set(required):
                raise ValueError(f"{name}: confirmations must cover every required subject exactly once")
            if any(item[rule["evidence_decision_field"]] != rule["accepted_decision"] for item in evidence if isinstance(item, dict)):
                raise ValueError(f"{name}: promotion requires confirm decisions only")
            receipt_field = rule.get("evidence_receipt_field")
            if isinstance(receipt_field, str):
                receipts = [item[receipt_field] for item in evidence if isinstance(item, dict)]
                if rule.get("require_unique_evidence_receipts") and len(receipts) != len(set(receipts)):
                    raise ValueError(f"{name}: confirm receipts must be unique")
                for path in rule.get("evidence_receipts_distinct_from_fields", []):
                    if _path_get(payload, str(path)) in receipts:
                        raise ValueError(f"{name}: proposal/promotion receipts cannot authorize a vote")
        elif kind == "epoch_semantics":
            epoch = _path_get(payload, str(rule["epoch_field"]))
            if epoch == 0:
                if _path_get(payload, "event_type") not in rule["zero_event_values"]:
                    raise ValueError(f"{name}: epoch 0 is lifecycle-only")
                if any(_path_get(payload, str(path)) is not None for path in rule["zero_null_fields"]):
                    raise ValueError(f"{name}: epoch 0 cannot carry authority")
            elif any(_path_get(payload, str(path)) is None for path in rule["positive_non_null_fields"]):
                raise ValueError(f"{name}: issued event requires a complete fence")
'''.splitlines()
    )
    lines.append("")
    for name, schema in defs.items():
        meta = _meta_of(schema)
        values = schema["enum"]
        screaming = _screaming(name)
        default = meta.get("default")
        lines.append("")
        lines.append(f"class {name}(enum.StrEnum):")
        lines.append(f'    """{_one_line(schema["description"])}"""')
        lines.append("")
        notes = meta["value_notes"]
        for value in values:
            member = f"{screaming}_{value.upper()}"
            lines.append(f"    {member} = {json.dumps(value, ensure_ascii=False)}  # {_one_line(notes[value])}")
        lines.append("")
        lines.append("    @classmethod")
        lines.append("    def values(cls) -> tuple[str, ...]:")
        lines.append('        """All canonical values in schema order."""')
        lines.append("        return tuple(member.value for member in cls)")
        lines.append("")
        lines.append("    @classmethod")
        lines.append("    def from_value(cls, value: str | None) -> " + f"{name} | None:")
        lines.append('        """Return the member for value, or None when unknown (caller must fail closed)."""')
        lines.append("        if value is None:")
        lines.append("            return None")
        lines.append("        try:")
        lines.append("            return cls(value)")
        lines.append("        except ValueError:")
        lines.append("            return None")
        lines.append("")
        literal = ", ".join(json.dumps(v, ensure_ascii=False) for v in values)
        lines.append(f"type {name}Value = Literal[{literal}]")
        members = ", ".join(f"{name}.{screaming}_{v.upper()}" for v in values)
        lines.append(f"ALL_{screaming}_VALUES: tuple[{name}, ...] = ({members})")
        if default is None:
            lines.append(f"{screaming}_DEFAULT: {name} | None = None")
        else:
            lines.append(f"{screaming}_DEFAULT: {name} = {name}.{screaming}_{default.upper()}")
    lines.append("")
    registry = ", ".join(f'"{name}": {name}' for name in defs)
    lines.append(f'ENUM_REGISTRY: dict[str, type[enum.Enum]] = {{{registry}}}')
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# PR-01 object contracts (section 9.6)")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append(f"OBJECT_CONTRACTS_VERSION: int = {objects_version}")
    lifecycle_map = {
        entry["name"]: {
            "lifecycle": entry["lifecycle"],
            "consumer_mode": entry["consumer_mode"],
            "new_producer": entry["new_producer"],
            "replacement": entry["replacement"],
        }
        for entry in contract_lifecycle
    }
    lines.append(f"CONTRACT_LIFECYCLE: dict[str, dict[str, object]] = {lifecycle_map!r}")
    lines.append(
        "CANONICAL_PRODUCER_CONTRACTS: tuple[str, ...] = "
        + repr(
            tuple(
                entry["name"]
                for entry in contract_lifecycle
                if entry["new_producer"] == "allowed"
            )
        )
    )
    lines.append(
        "MIGRATION_ONLY_CONTRACTS: tuple[str, ...] = "
        + repr(
            tuple(
                entry["name"]
                for entry in contract_lifecycle
                if entry["consumer_mode"] == "migration_only"
            )
        )
    )
    lines.append("")
    lines.append("def is_new_producer_contract(name: str) -> bool:")
    lines.append("    lifecycle = CONTRACT_LIFECYCLE.get(name)")
    lines.append("    return lifecycle is not None and lifecycle[\"new_producer\"] == \"allowed\"")
    lines.append("")
    lines.append("def require_new_producer_contract(name: str) -> None:")
    lines.append("    if is_new_producer_contract(name):")
    lines.append("        return")
    lines.append("    lifecycle = CONTRACT_LIFECYCLE.get(name)")
    lines.append("    replacement = lifecycle.get(\"replacement\") if lifecycle is not None else None")
    lines.append("    raise ValueError(f\"{name}: forbidden for new producers; replacement={replacement}\")")
    invariant_registry = {
        name: tuple(_normalized_invariants(schema))
        for name, schema in object_defs.items()
        if _normalized_invariants(schema)
    }
    lines.append(
        "OBJECT_INVARIANTS: dict[str, tuple[dict[str, Any], ...]] = "
        + repr(invariant_registry)
    )
    context_hash_inputs = {
        name: tuple(schema["x-memoria-context-hash-inputs"])
        for name, schema in object_defs.items()
        if "x-memoria-context-hash-inputs" in schema
    }
    lines.append(
        "CONTEXT_HASH_INPUTS: dict[str, tuple[str, ...]] = "
        + repr(context_hash_inputs)
    )
    lines.append("")
    object_enum_names: list[str] = []
    for name, schema in object_defs.items():
        if _definition_kind(schema) != "enum":
            continue
        object_enum_names.append(name)
        values = schema["enum"]
        screaming = _screaming(name)
        lines.append("")
        lines.append(f"class {name}(enum.StrEnum):")
        lines.append(f'    """{_one_line(schema["description"])}"""')
        lines.append("")
        for value in values:
            lines.append(f"    {screaming}_{value.upper()} = {json.dumps(value, ensure_ascii=False)}")
        lines.append("")
        lines.append("    @classmethod")
        lines.append("    def values(cls) -> tuple[str, ...]:")
        lines.append("        return tuple(member.value for member in cls)")
        lines.append("")
        literal = ", ".join(json.dumps(v, ensure_ascii=False) for v in values)
        lines.append(f"type {name}Value = Literal[{literal}]")
        members = ", ".join(f"{name}.{screaming}_{v.upper()}" for v in values)
        lines.append(f"ALL_{screaming}_VALUES: tuple[{name}, ...] = ({members})")
    lines.append("")
    enum_registry = ", ".join(f'"{name}": {name}' for name in object_enum_names)
    lines.append(f"OBJECT_ENUM_REGISTRY: dict[str, type[enum.Enum]] = {{{enum_registry}}}")
    lines.append("")
    canonical: set[str] = set(defs)
    for name, schema in object_defs.items():
        kind = _definition_kind(schema)
        if kind == "enum":
            continue
        if kind == "extend":
            base_name = schema["x-memoria-extends"]
            base_props = set(object_defs[base_name].get("properties", {}))
            extend_fields = [
                field
                for field in _object_fields(name, schema, object_defs, canonical)
                if field.name not in base_props
            ]
            lines.append("")
            lines.append(f"class {name}({base_name}):")
            lines.append(f'    """{_one_line(schema["description"])}"""')
            lines.append("")
            for field in extend_fields:
                lines.append("    " + _python_field_line(field))
            continue
        lines.append("")
        lines.append(f"class {name}(BaseModel):")
        lines.append(f'    """{_one_line(schema["description"])}"""')
        lines.append('    model_config = ConfigDict(extra="forbid", frozen=True)')
        lines.append("")
        fields = _object_fields(name, schema, object_defs, canonical)
        for field in fields:
            lines.append("    " + _python_field_line(field))
        for field in fields:
            if not field.has_const:
                continue
            lines.append("")
            lines.append(f"    @field_validator({json.dumps(field.name)}, mode=\"before\")")
            lines.append("    @classmethod")
            lines.append(f"    def _{field.name}_const(cls, value: object) -> object:")
            lines.append(f"        if value != {json.dumps(field.const_value, ensure_ascii=False)}:")
            lines.append(f'            raise ValueError("{field.name}: const mismatch")')
            lines.append("        return value")
        for field in fields:
            if field.format != "date-time":
                continue
            lines.append("")
            lines.append(f"    @field_validator({json.dumps(field.name)}, mode=\"before\")")
            lines.append("    @classmethod")
            lines.append(f"    def _{field.name}_rfc3339(cls, value: object) -> object:")
            lines.append("        if value is None:")
            lines.append("            return None")
            lines.append("        if not isinstance(value, str) or not RFC3339_STRICT_PATTERN.fullmatch(value):")
            lines.append(f'            raise ValueError("{field.name}: must be RFC3339 string with T separator and offset/Z")')
            lines.append('        return value.replace("t", "T").replace("z", "Z")')
        for field in fields:
            if not field.unique_items:
                continue
            lines.append("")
            lines.append(f"    @field_validator({json.dumps(field.name)})")
            lines.append("    @classmethod")
            lines.append(f"    def _{field.name}_unique(cls, value: tuple[object, ...]) -> tuple[object, ...]:")
            lines.append("        if not _unique_json_items(value):")
            lines.append(f'            raise ValueError("{field.name}: items must be unique")')
            lines.append("        return value")
        lines.extend(_python_invariant_lines(name, schema))
    lines.append("")
    return "\n".join(lines) + "\n"


def _py_schema_annotation(schema: dict[str, Any]) -> str:
    """Render a recursive strict Pydantic annotation for the supported schema subset."""

    if "$ref" in schema:
        return str(schema["$ref"].rsplit("/", 1)[-1])
    if "enum" in schema:
        return "Literal[" + ", ".join(
            json.dumps(value, ensure_ascii=False) for value in schema["enum"]
        ) + "]"
    json_type = schema.get("type")
    if json_type == "string":
        if schema.get("format") == "date-time":
            return "Annotated[datetime, AwareDatetime()]"
        kwargs: list[str] = ["strict=True"]
        if schema.get("minLength") is not None:
            kwargs.append(f"min_length={schema['minLength']}")
        if schema.get("maxLength") is not None:
            kwargs.append(f"max_length={schema['maxLength']}")
        if schema.get("pattern") is not None:
            kwargs.append(f"pattern={json.dumps(schema['pattern'])}")
        return f"Annotated[str, Field({', '.join(kwargs)})]"
    if json_type == "integer":
        kwargs = ["strict=True"]
        if schema.get("minimum") is not None:
            kwargs.append(f"ge={schema['minimum']}")
        if schema.get("maximum") is not None:
            kwargs.append(f"le={schema['maximum']}")
        return f"Annotated[int, Field({', '.join(kwargs)})]"
    if json_type == "number":
        kwargs = ["strict=True", "allow_inf_nan=False"]
        if schema.get("minimum") is not None:
            kwargs.append(f"ge={schema['minimum']}")
        if schema.get("maximum") is not None:
            kwargs.append(f"le={schema['maximum']}")
        return f"Annotated[float, Field({', '.join(kwargs)})]"
    if json_type == "boolean":
        return "Annotated[bool, Field(strict=True)]"
    if json_type == "array":
        item = _py_schema_annotation(cast(dict[str, Any], schema["items"]))
        base = f"tuple[{item}, ...]"
        kwargs = []
        if schema.get("minItems") is not None:
            kwargs.append(f"min_length={schema['minItems']}")
        if schema.get("maxItems") is not None:
            kwargs.append(f"max_length={schema['maxItems']}")
        return f"Annotated[{base}, Field({', '.join(kwargs)})]" if kwargs else base
    if json_type == "object":
        additional = schema.get("additionalProperties")
        value_type = (
            _py_schema_annotation(cast(dict[str, Any], additional))
            if isinstance(additional, dict)
            else "object"
        )
        base = f"dict[str, {value_type}]"
        if schema.get("maxProperties") is not None:
            return f"Annotated[{base}, Field(max_length={schema['maxProperties']})]"
        return base
    return "object"


def _py_annotation(field: FieldSpec) -> str:
    base = _py_schema_annotation(field.value_schema)
    return f"{base} | None" if field.nullable else base


def _python_field_line(field: FieldSpec) -> str:
    ann = _py_annotation(field)
    return f"{field.name}: {ann}" if field.required else f"{field.name}: {ann} = None"


def _python_invariant_lines(name: str, schema: dict[str, Any]) -> list[str]:
    rules = _normalized_invariants(schema)
    if not rules:
        return []
    return [
        "",
        "    @model_validator(mode=\"after\")",
        "    def _contract_invariants(self) -> Self:",
        f"        _validate_contract_invariants({name!r}, self.model_dump(mode=\"json\"), OBJECT_INVARIANTS[{name!r}])",
        "        return self",
    ]

    # Kept below as an intentionally unreachable historical emitter until all
    # downstream consumers have migrated to the shared invariant DSL.
    has_rules = any(
        key in schema
        for key in (
            "x-memoria-paired-arrays",
            "x-memoria-value-pairs",
            "x-memoria-non-null-if",
            "x-memoria-distinct-fields",
            "x-memoria-approval-subjects",
            "x-memoria-confirmation-coverage",
            "x-memoria-epoch-semantics",
            "x-memoria-forbidden-values",
            "x-memoria-unique-by",
        )
    )
    if not has_rules:
        return []
    lines = ["", "    @model_validator(mode=\"after\")", "    def _contract_invariants(self) -> Self:"]
    for left, right in schema.get("x-memoria-paired-arrays", []):
        lines.append(f"        if len(self.{left}) != len(self.{right}):")
        lines.append(f'            raise ValueError("{left}/{right}: aligned arrays must have equal length")')
    for rule in schema.get("x-memoria-value-pairs", []):
        left = rule["left_field"]
        right = rule["right_field"]
        pairs = rule["pairs"]
        lines.append(f"        _pairs_{left}_{right} = {pairs!r}")
        lines.append(f"        if str(self.{left}) in _pairs_{left}_{right} and str(self.{right}) != _pairs_{left}_{right}[str(self.{left})]:")
        lines.append(f'            raise ValueError("{left}/{right}: restricted authority pair mismatch")')
        if rule["bidirectional"]:
            lines.append(f"        _inverse_{left}_{right} = {{value: key for key, value in _pairs_{left}_{right}.items()}}")
            lines.append(f"        if str(self.{right}) in _inverse_{left}_{right} and str(self.{left}) != _inverse_{left}_{right}[str(self.{right})]:")
            lines.append(f'            raise ValueError("{left}/{right}: restricted authority pair mismatch")')
    for rule in schema.get("x-memoria-non-null-if", []):
        trigger = rule["field"]
        equals = repr(rule["equals"])
        for target in rule["non_null_fields"]:
            lines.append(f"        if self.{trigger} == {equals} and self.{target} is None:")
            lines.append(f'            raise ValueError("{target}: required by {trigger}")')
    for left, right in schema.get("x-memoria-distinct-fields", []):
        lines.append(f"        if self.{left} == self.{right}:")
        lines.append(f'            raise ValueError("{left}/{right}: values must be distinct")')
    approval = schema.get("x-memoria-approval-subjects")
    if isinstance(approval, dict):
        proposer = approval["proposer_field"]
        co_subjects = approval["co_subjects_field"]
        required = approval["required_field"]
        lines.append(f"        _expected_approvals = {{self.{proposer}, *self.{co_subjects}}}")
        lines.append(f"        if set(self.{required}) != _expected_approvals or len(self.{required}) != len(_expected_approvals):")
        lines.append(f'            raise ValueError("{required}: must equal proposer plus co-subjects")')
    coverage = schema.get("x-memoria-confirmation-coverage")
    if isinstance(coverage, dict):
        required = coverage["required_subject_ids_field"]
        evidence = coverage["evidence_field"]
        subject = coverage["evidence_subject_field"]
        decision = coverage["evidence_decision_field"]
        accepted = repr(coverage["accepted_decision"])
        lines.append(f"        _evidence_subjects = [item.{subject} for item in self.{evidence}]")
        lines.append(f"        if any(str(item.{decision}) != {accepted} for item in self.{evidence}):")
        lines.append(f'            raise ValueError("{evidence}: every approval must carry the accepted decision")')
        lines.append(f"        if set(_evidence_subjects) != set(self.{required}) or len(_evidence_subjects) != len(set(_evidence_subjects)):")
        lines.append(f'            raise ValueError("{evidence}: must cover every required subject exactly once")')
        receipt_field = coverage.get("evidence_receipt_field")
        if isinstance(receipt_field, str):
            lines.append(f"        _approval_receipts = [item.{receipt_field} for item in self.{evidence}]")
            if coverage.get("require_unique_evidence_receipts"):
                lines.append("        if len(_approval_receipts) != len(set(_approval_receipts)):")
                lines.append(f'            raise ValueError("{evidence}: approval receipts must be unique")')
            for target in coverage.get("evidence_receipts_distinct_from_fields", []):
                lines.append(f"        if self.{target} in _approval_receipts:")
                lines.append(f'            raise ValueError("{evidence}: approval receipt cannot reuse {target}")')
    epoch = schema.get("x-memoria-epoch-semantics")
    if isinstance(epoch, dict):
        epoch_field = epoch["epoch_field"]
        allowed = tuple(epoch["zero_event_values"])
        lines.append(f"        if self.{epoch_field} == 0:")
        lines.append(f"            if str(self.event_type) not in {allowed!r}:")
        lines.append('                raise ValueError("event_type: epoch 0 is lifecycle-only")')
        for target in epoch["zero_null_fields"]:
            lines.append(f"            if self.{target} is not None:")
            lines.append(f'                raise ValueError("{target}: epoch 0 requires null")')
        lines.append("        else:")
        for target in epoch["positive_non_null_fields"]:
            lines.append(f"            if self.{target} is None:")
            lines.append(f'                raise ValueError("{target}: issued events require a complete fence")')
    for rule in schema.get("x-memoria-forbidden-values", []):
        target = rule["field"]
        values = tuple(rule["values"])
        lines.append(f"        if str(self.{target}) in {values!r}:")
        lines.append(f'            raise ValueError("{target}: forbidden fail-closed value")')
    for rule in schema.get("x-memoria-unique-by", []):
        target = rule["field"]
        item_field = rule["item_field"]
        lines.append(f"        _keys_{target} = [item.{item_field} for item in self.{target}]")
        lines.append(f"        if len(_keys_{target}) != len(set(_keys_{target})):")
        lines.append(f'            raise ValueError("{target}: {item_field} must be unique")')
    lines.append("        return self")
    return lines
def _generate_commonjs(
    defs: dict[str, dict[str, Any]],
    object_defs: dict[str, dict[str, Any]],
    contract_lifecycle: tuple[dict[str, Any], ...],
    schema_version: int,
    objects_version: int,
    schema_hash: str,
) -> str:
    """Generate a dependency-free CommonJS artifact for WeChat and Node consumers."""
    lines = [
        "/*",
        *[f" * {header_line}" for header_line in HEADER.splitlines()],
        f" * Source hash: sha256:{schema_hash}",
        " *",
        " * Dependency-free CommonJS for the WeChat JavaScript runtime and Node tests.",
        " */",
        '"use strict";',
        "",
        f"const CONTRACTS_SCHEMA_VERSION = {schema_version};",
        f"const OBJECT_CONTRACTS_VERSION = {objects_version};",
        f"const SOURCE_HASH = {json.dumps(schema_hash)};",
        f"const SOURCE_SCHEMA = {json.dumps(SCHEMA_ID)};",
        "",
        "const CONTRACT_LIFECYCLE = Object.freeze({",
    ]
    for entry in contract_lifecycle:
        lifecycle = {
            "lifecycle": entry["lifecycle"],
            "consumer_mode": entry["consumer_mode"],
            "new_producer": entry["new_producer"],
            "replacement": entry["replacement"],
        }
        lines.append(
            f"  {json.dumps(entry['name'])}: Object.freeze("
            f"{json.dumps(lifecycle, ensure_ascii=False, separators=(',', ':'))}),"
        )
    lines.extend(
        [
            "});",
            "",
            "const CANONICAL_PRODUCER_CONTRACTS = Object.freeze([",
        ]
    )
    for entry in contract_lifecycle:
        if entry["new_producer"] == "allowed":
            lines.append(f"  {json.dumps(entry['name'])},")
    lines.extend(
        [
            "]);",
            "",
            "const MIGRATION_ONLY_CONTRACTS = Object.freeze([",
        ]
    )
    for entry in contract_lifecycle:
        if entry["consumer_mode"] == "migration_only":
            lines.append(f"  {json.dumps(entry['name'])},")
    lines.extend(
        [
            "]);",
            "",
            "function isNewProducerContract(name) {",
            "  const lifecycle = CONTRACT_LIFECYCLE[name];",
            '  return Boolean(lifecycle && lifecycle.new_producer === "allowed");',
            "}",
            "",
            "function requireNewProducerContract(name) {",
            "  if (isNewProducerContract(name)) return;",
            "  const lifecycle = CONTRACT_LIFECYCLE[name];",
            "  const replacement = lifecycle ? lifecycle.replacement : null;",
            '  throw new Error(`${name}: forbidden for new producers; replacement=${replacement}`);',
            "}",
            "",
        ]
    )

    for name, schema in defs.items():
        values = cast(list[str], schema["enum"])
        meta = _meta_of(schema)
        screaming = _screaming(name)
        keys = [_commonjs_key(name, value) for value in values]
        if len(set(keys)) != len(keys):
            _fail(f"{name}: duplicate CommonJS property keys {keys!r}")
        lines.append(f"const {name} = Object.freeze({{")
        for key, value in zip(keys, values, strict=True):
            lines.append(f"  {json.dumps(key)}: {json.dumps(value, ensure_ascii=False)},")
        lines.extend(
            [
                "});",
                f"const {screaming}_VALUES = Object.freeze("
                f"{json.dumps(values, ensure_ascii=False, separators=(',', ':'))});",
                f"const {screaming}_DEFAULT = "
                f"{json.dumps(meta.get('default'), ensure_ascii=False)};",
                f"function is{name}(value) {{",
                f'  return typeof value === "string" && {screaming}_VALUES.includes(value);',
                "}",
                "",
            ]
        )

    lines.append("const ENUM_REGISTRY = Object.freeze({")
    for name, schema in defs.items():
        meta = _meta_of(schema)
        screaming = _screaming(name)
        lines.extend(
            [
                f"  {json.dumps(name)}: Object.freeze({{",
                f"    values: {screaming}_VALUES,",
                f"    default: {screaming}_DEFAULT,",
                f"    contract_version: {meta['contract_version']},",
                f"    missing_value_policy: {json.dumps(meta['missing_value_policy'])},",
                f"    guard: is{name},",
                "  }),",
            ]
        )
    lines.extend(["});", ""])

    context_hash_inputs = {
        name: schema["x-memoria-context-hash-inputs"]
        for name, schema in object_defs.items()
        if "x-memoria-context-hash-inputs" in schema
    }
    lines.append("const CONTEXT_HASH_INPUTS = Object.freeze({")
    for name, paths in context_hash_inputs.items():
        lines.append(
            f"  {json.dumps(name)}: Object.freeze("
            f"{json.dumps(paths, ensure_ascii=False, separators=(',', ':'))}),"
        )
    lines.extend(["});", "", "module.exports = {"])
    lines.extend(
        [
            "  CONTRACTS_SCHEMA_VERSION,",
            "  OBJECT_CONTRACTS_VERSION,",
            "  SOURCE_HASH,",
            "  SOURCE_SCHEMA,",
            "  CONTRACT_LIFECYCLE,",
            "  CANONICAL_PRODUCER_CONTRACTS,",
            "  MIGRATION_ONLY_CONTRACTS,",
            "  CONTEXT_HASH_INPUTS,",
            "  ENUM_REGISTRY,",
            "  isNewProducerContract,",
            "  requireNewProducerContract,",
        ]
    )
    for name in defs:
        screaming = _screaming(name)
        lines.extend(
            [
                f"  {name},",
                f"  {screaming}_VALUES,",
                f"  {screaming}_DEFAULT,",
                f"  is{name},",
            ]
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


OUTPUT_FILES: dict[str, str] = {
    "packages/contracts/generated/python/multi_subject_contracts.py": "python",
    "apps/miniprogram/generated/multi-subject-contracts.js": "commonjs",
}


def build_outputs(root: Path) -> dict[Path, str]:
    schema_path = root / SCHEMA_REL_PATH
    if not schema_path.is_file():
        raise FileNotFoundError(f"canonical schema not found: {schema_path}")
    data = load_schema(schema_path)
    schema_hash = hashlib.sha256(schema_path.read_bytes()).hexdigest()
    defs: dict[str, dict[str, Any]] = data["$defs"]
    object_defs: dict[str, dict[str, Any]] = _validate_objects(data)
    schema_version: int = data["properties"]["schema_version"]["const"]
    objects_version: int = data["objects"]["properties"]["objects_version"]["const"]
    contract_lifecycle = _contract_lifecycle(data)
    generators = {
        "python": _generate_python,
        "commonjs": _generate_commonjs,
    }
    outputs: dict[Path, str] = {}
    for rel, language in OUTPUT_FILES.items():
        outputs[root / rel] = (
            generators[language](
                defs,
                object_defs,
                contract_lifecycle,
                schema_version,
                objects_version,
                schema_hash,
            ).rstrip("\n")
            + "\n"
        )
    return outputs


def run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Memoria multi-subject canonical contract artifacts.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write generated artifacts (default)")
    mode.add_argument("--check", action="store_true", help="verify on-disk artifacts match fresh generation; exit 1 on drift")
    parser.add_argument("--output-root", type=Path, default=None, help="repository root (default: two levels above this script)")
    args = parser.parse_args(argv)
    root = (args.output_root or Path(__file__).resolve().parent.parent).resolve()
    outputs = build_outputs(root)
    if args.check:
        drifted: list[Path] = []
        for path, content in outputs.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                drifted.append(path)
        if drifted:
            for path in drifted:
                print(f"DRIFT: {path.relative_to(root)}")
            print(f"multi-subject contracts: {len(drifted)} artifact(s) out of date; run the generator with --write")
            return 1
        print(f"multi-subject contracts: {len(outputs)} artifact(s) in sync (no diff)")
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"WROTE: {path.relative_to(root)}")
    print(f"multi-subject contracts: generated {len(outputs)} artifact(s)")
    return 0


if __name__ == "__main__":
    sys.exit(run())
